### ISSUE TITLE
Não funcionou no meu PC.

### ISSUE THREAD

**Issue by yuri-potatoq** [NiumXp/regex4noobs#1]
Fui tentar ler aqui no meu pc e não entendi nada, mas no celular eu entendo.

**Comment by phiberber** [comment]
Bom dia @yuri-potatoq.

Poderia ser mais específico sobre que página da regex4noobs que você não foi capaz de acessar ou entender? Por acaso o problema é relacionado a alinhamento de texto aonde o mesmo fica melhor representado no celular?
